// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241206154218_AddUserAndOrderEntity")]
    partial class AddUserAndOrderEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.OrderEntities.CustomerDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("CustomerDetails");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("OrderId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerDetailId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerDetailId");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.StatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique();

                    b.ToTable("StatusTypes");
                });

            modelBuilder.Entity("API.Entities.UserEntities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Calibre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Calibres");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.CaseMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Material")
                        .IsUnique();

                    b.ToTable("CaseMaterials");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Crystal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Material")
                        .IsUnique();

                    b.ToTable("Crystals");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Dial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Colour")
                        .IsUnique();

                    b.ToTable("Dials");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.MovementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("MovementTypes");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("WatchId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.PowerReserve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Duration")
                        .IsUnique();

                    b.ToTable("PowerReserves");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("WatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WatchId")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.StrapBraceletMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Material")
                        .IsUnique();

                    b.ToTable("StrapBraceletMaterials");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Watch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CalibreId")
                        .HasColumnType("integer");

                    b.Property<int>("CaseMaterialId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("CrystalId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DialId")
                        .HasColumnType("integer");

                    b.Property<bool>("Lume")
                        .HasColumnType("boolean");

                    b.Property<int>("MovementTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherSpecifications")
                        .HasColumnType("text");

                    b.Property<int>("PowerReserveId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StrapBraceletMaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("WatchCaseMeasurementsId")
                        .HasColumnType("integer");

                    b.Property<int>("WatchTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("WaterResistanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CalibreId");

                    b.HasIndex("CaseMaterialId");

                    b.HasIndex("CrystalId");

                    b.HasIndex("DialId");

                    b.HasIndex("MovementTypeId");

                    b.HasIndex("PowerReserveId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("StrapBraceletMaterialId");

                    b.HasIndex("WatchCaseMeasurementsId");

                    b.HasIndex("WatchTypeId");

                    b.HasIndex("WaterResistanceId");

                    b.ToTable("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.WatchCaseMeasurements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Diameter")
                        .HasColumnType("double precision");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<double>("LugWidth")
                        .HasColumnType("double precision");

                    b.Property<double>("Thickness")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Diameter", "Length", "LugWidth", "Thickness")
                        .IsUnique();

                    b.ToTable("WatchCaseMeasurements");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.WatchType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("WatchTypes");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.WaterResistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Resistance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Resistance")
                        .IsUnique();

                    b.ToTable("WaterResistances");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.CustomerDetail", b =>
                {
                    b.HasOne("API.Entities.UserEntities.AppUser", "AppUser")
                        .WithMany("CustomerDetails")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.Item", b =>
                {
                    b.HasOne("API.Entities.OrderEntities.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.OrderEntities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.Order", b =>
                {
                    b.HasOne("API.Entities.OrderEntities.CustomerDetail", "CustomerDetail")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.OrderEntities.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerDetail");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Photo", b =>
                {
                    b.HasOne("API.Entities.WatchEntities.Watch", "Watch")
                        .WithMany("Photos")
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Stock", b =>
                {
                    b.HasOne("API.Entities.WatchEntities.Watch", "Watch")
                        .WithOne("Stock")
                        .HasForeignKey("API.Entities.WatchEntities.Stock", "WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Watch", b =>
                {
                    b.HasOne("API.Entities.WatchEntities.Brand", "Brand")
                        .WithMany("Watches")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.Calibre", "Calibre")
                        .WithMany("Watches")
                        .HasForeignKey("CalibreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.CaseMaterial", "CaseMaterial")
                        .WithMany("Watches")
                        .HasForeignKey("CaseMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.Crystal", "Crystal")
                        .WithMany("Watches")
                        .HasForeignKey("CrystalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.Dial", "Dial")
                        .WithMany("Watches")
                        .HasForeignKey("DialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.MovementType", "MovementType")
                        .WithMany("Watches")
                        .HasForeignKey("MovementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.PowerReserve", "PowerReserve")
                        .WithMany("Watches")
                        .HasForeignKey("PowerReserveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.StrapBraceletMaterial", "StrapBraceletMaterial")
                        .WithMany("Watches")
                        .HasForeignKey("StrapBraceletMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.WatchCaseMeasurements", "WatchCaseMeasurements")
                        .WithMany("Watches")
                        .HasForeignKey("WatchCaseMeasurementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.WatchType", "WatchType")
                        .WithMany("Watches")
                        .HasForeignKey("WatchTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.WatchEntities.WaterResistance", "WaterResistance")
                        .WithMany("Watches")
                        .HasForeignKey("WaterResistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Calibre");

                    b.Navigation("CaseMaterial");

                    b.Navigation("Crystal");

                    b.Navigation("Dial");

                    b.Navigation("MovementType");

                    b.Navigation("PowerReserve");

                    b.Navigation("StrapBraceletMaterial");

                    b.Navigation("WatchCaseMeasurements");

                    b.Navigation("WatchType");

                    b.Navigation("WaterResistance");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.CustomerDetail", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.ItemType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("API.Entities.OrderEntities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("API.Entities.UserEntities.AppUser", b =>
                {
                    b.Navigation("CustomerDetails");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Brand", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Calibre", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.CaseMaterial", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Crystal", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Dial", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.MovementType", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.PowerReserve", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.StrapBraceletMaterial", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.Watch", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.WatchCaseMeasurements", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.WatchType", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("API.Entities.WatchEntities.WaterResistance", b =>
                {
                    b.Navigation("Watches");
                });
#pragma warning restore 612, 618
        }
    }
}
